'use strict';

/**
 * @ngdoc function
 * @name outpathsApp.controller:HealingCtrl
 * @description
 * # HealingCtrl
 * Controller of the outpathsApp
 */
angular.module('outpathsApp')
  .controller('HealingCtrl', function ($scope, $rootScope) {
    $scope.awesomeThings = [
      'HTML5 Boilerplate',
      'AngularJS',
      'Karma'
    ];
    $scope.healingList = [
      'Meditations',
      'Reconciliations',
      'Practicalities',
      'Donate',
      'Volunteer',
      'Gifts'
    ];
    $rootScope.bodyClass = 'healing-page';
    $scope.sideBarToggle = true;
    $scope.activeSideItem = 6;
    $scope.sideBarToggle = true;
    $scope.toggleSidebar = function(){
      $scope.sideBarToggle = !$scope.sideBarToggle;
    };
    $scope.hideSidebar = function(){
      $scope.sideBarToggle = true;
    };
    $scope.responseJson = {
      quotes:[
        {
          image:'../images/emily.jpg',
          title:'Emily Dickinson',
          quote:'My life closed twice before its close; It yet remains to see If Immortality unveil A third event to me, ' +
          'So huge, so hopeless to conceive, As these that twice befell. Parting is all we know of heaven, And all we need of hell.'
        },
        {
          image:'../images/einstein.jpg',
          title:'Albert Einstein',
          quote: 'Man would indeed be in a poor way if he had to be restrained by fear of punishment and hope of reward after death.'
        },
        {
          image:'../images/einstein.jpg',
          title:'Thomas Paine',
          quote:'I believe in one God, and no more; and' +
          'I hope for happiness beyond this life. I believe in the equality of man; and I believe that religious ' +
          'duties consist in doing justice, loving mercy, and endeavoring to make our fellow creatures happy.'
        }
      ],
      donate:[
        {
          path:'../images/action_against_hunger.png',
          url:'http://www.actionagainsthunger.org'
        },
        {
          path:'../images/afa.png',
          url:'http://www.afa.org'
        },
        {
          path:'../images/american_brain_tumor_asc.png',
          url:'http://www.abta.org'
        },
        {
          path:'../images/american_cancer_society.png',
          url:'http://www.cancer.org'
        },
        {
          path:'../images/american_heart_asc.png',
          url:'http://www.heart.org'
        },
        {
          path:'../images/american_liver_foundation.png',
          url:'http://www.liverfoundation.org'
        },
        {
          path:'../images/american_lung_asc.png',
          url:'http://www.lung.org'
        },
        {
          path:'../images/amnesty_international.png',
          url:'http://www.amnesty.org'
        },
        {
          path:'../images/apda.png',
          url:'http://www.apdaparkinson.org'
        },
        {
          path:'../images/asha_for_education.png',
          url:'http://www.ashanet.org'
        },
        {
          path:'../images/badi_foundation.png',
          url:'http://www.badi-foundation.org/en'
        },
        {
          path:'../images/bread_for_world.png',
          url:'http://www.bread.org'
        },
        {
          path:'../images/center_for_victims.png',
          url:'http://www.cvt.org'
        },
        {
          path:'../images/child_defense_fund.png',
          url:'http://www.childrendefense.org'
        },
        {
          path:'../images/family_care.png',
          url:'http://www.familycareintl.org/en/home'
        },
        {
          path:'../images/fisher_house.png',
          url:'http://www.fisherhouse.org'
        },
        {
          path:'../images/food_for_hungry.png',
          url:'http://www.fh.org'
        },
        {
          path:'../images/half_the_sky.png',
          url:'http://www.halfthesky.org/en'
        },
        {
          path:'../images/heifer_international.png',
          url:'http://www.heifer.org'
        },
        {
          path:'../images/hispanic_scholarship.png',
          url:'http://www.hsf.net'
        },
        {
          path:'../images/jane_goodall.png',
          url:'http://www.janegoodall.org'
        },
        {
          path:'../images/jewish_national.png',
          url:'http://www.jnf.org'
        },
        {
          path:'../images/maya_archaeology.png',
          url:'http://mayaarchaeology.org/'
        },
        {
          path:'../images/mercy_corps.png',
          url:'http://www.mercycorps.org/'
        },
        {
          path:'../images/parkinson_disease_foundation.png',
          url:'http://www.pdf.org/'
        },
        {
          path:'../images/psi.png',
          url:'http://www.psi.org/'
        },
        {
          path:'../images/unicef.png',
          url:'http://www.unicef.org/'
        },
        {
          path:'../images/wheelchair_foundation.png',
          url:'http://www.wheelchairfoundation.org/'
        },
        {
          path:'../images/clinton_foundation.png',
          url:'http://www.clintonfoundation.org/'
        },
        {
          path:'../images/redcross_china.png',
          url:'http://www.redcross.org.cn/hhzh'
        },
        {
          path:'../images/world_villages.png',
          url:'http://www.worldvillages.org/'
        },
        {
          path:'../images/world_wildlife_foundation.png',
          url:'http://gifts.worldwildlife.org/'
        },
        {
          path:'../images/wounded_warrior_project.png',
          url:'http://www.woundedwarriorproject.org/'
        }
      ],
      volunteer:[
        {
          path:'../images/ymca.png',
          url:'http://www.ymca.net/'
        },
        {
          path:'../images/nature_conservancy.png',
          url:'http://www.nature.org/'
        },
        {
          path:'../images/special_olympics.png',
          url:'http://www.specialolympics.org/'
        },{
          path:'../images/save_the_children.png',
          url:'http://www.savethechildren.org/'
        },{
          path:'../images/oxfam_international.png',
          url:'http://www.oxfam.org/'
        },{
          path:'../images/mda.png',
          url:'http://mda.org/'
        },{
          path:'../images/leukemia_society.png',
          url:'http://www.lls.org/'
        },{
          path:'../images/rescue_committee.png',
          url:'http://www.rescue.org/'
        },{
          path:'../images/doctors_without_borders.png',
          url:'http://www.doctorswithoutborders.org/'
        },
        {
          path:'../images/cystic_fibrosis_foundation.png',
          url:'http://www.cff.org/'
        },
        {
          path:'../images/boys_girls_club.png',
          url:'http://www.bgca.org/'
        },{
          path:'../images/boy_scouts.png',
          url:'http://www.scouting.org/'
        },{
          path:'../images/american_jewish.png',
          url:'http://www.ajws.org/'
        },
      ],
      gifts:{
        cards:[
          {
            path:'../images/gift-tile-SAG.jpg',
            url:'http://www.sagessedesigns.com/Sagesse_Designs/Sagesse_Designs_Home.html'
          },
          {
            path:'../images/gift-tile-JAC.jpg',
            url:'http://www.jacquielawson.com/'
          },
          {
            path:'../images/gift-tile-BMN.jpg',
            url:'http://www.bluemountain.com/ecards'
          },
          {
            path:'../images/gift-tile-PLP.jpg',
            url:'http://www.paperlesspost.com/'
          },
        ],
        activities:[
          {
            path:'../images/gift-tile-CSA.jpg',
            url:'http://www.carlasonheim.com/store/'
          }
        ],
        things:[
          {
            path:'../images/gift-tile-SGT.jpg',
            url:'http://www.withsympathygifts.com/'
          },
          {
            path:'../images/gift-tile-EBW.jpg',
            url:'http://www.englishbasketrywillows.com/'
          },
          {
            path:'../images/gift-tile-ESK.jpg',
            url:'http://www.earthsake.com/'
          },
          {
            path:'../images/gift-tile-SPE.jpg',
            url:'http://www.simonpearce.com/'
          },
          {
            path:'../images/gift-tile-DBW.jpg',
            url:'http://www.davisblanchardwindchimes.com/'
          }
        ],
        food:[
          {
            path:'../images/gift-tile-ZMO.jpg',
            url:'http://www.zingermans.com/'
          },
          {
            path:'../images/gift-tile-HFR.jpg',
            url:'http://www.hogsfly.com/Category.php?category_id=1'
          },
          {
            path:'../images/gift-tile-ENS.jpg',
            url:'http://www.enstrom.com/'
          },
          {
            path:'../images/gift-tile-SMC.jpg',
            url:'http://www.senormurphy.com/x/'
          },
          {
            path:'../images/gift-tile-WMM.jpg',
            url:'http://www.wondermade.com/'
          },
          {
            path:'../images/gift-tile-LFB.jpg',
            url:'http://www.linnsfruitbin.com/'
          },
          {
            path:'../images/gift-tile-TFB.jpg',
            url:'http://www.twofishbaking.com/'
          },
          {
            path:'../images/gift-tile-KCC.jpg',
            url:'http://www.karascupcakes.com/'
          },
          {
            path:'../images/gift-tile-WOS.jpg',
            url:'http://www.williams-sonoma.com/'
          },
          {
            path:'../images/gift-tile-ROT.jpg',
            url:'http://republicoftea.com/'
          },
          {
            path:'../images/gift-tile-PCT.jpg',
            url:'http://www.peets.com/'
          },
          {
            path:'../images/gift-tile-INE.jpg',
            url:'http://incredibleedibles.net/'
          },
          {
            path:'../images/gift-tile-MSF.jpg',
            url:'http://www.munchery.com/'
          },
          {
            path:'../images/gift-tile-TFF.jpg',
            url:'http://www.taitfarmfoods.com/'
          },
          {
            path:'../images/gift-tile-WPY.jpg',
            url:'http://www.worldpantry.com/'
          }
        ],
        wineries:[
          {
            path:'../images/gift-tile-CHW.jpg',
            url:'http://www.clayhousewines.com/'
          },
          {
            path:'../images/gift-tile-TFW.jpg',
            url:'http://www.fogartywinery.com/'
          },
          {
            path:'../images/gift-tile-NVD.jpg',
            url:'http://www.navarrowine.com/'
          },
          {
            path:'../images/gift-tile-PVW.jpg',
            url:'http://www.primaristorante.com/'
          }
        ],
        plants:[
          {
            path:'../images/gift-tile-GPL.jpg',
            url:'http://www.ftd.com/seeds-of-life-memory-tree-prd/sl01'
          },
          {
            path:'../images/gift-tile-TOA.jpg',
            url:'http://www.treesofantiquity.com/'
          },
          {
            path:'../images/gift-tile-ADF.jpg',
            url:'http://shop.arborday.org/content.aspx?page=Commemorative'
          }
        ],
        gift_certificates:[
          {
            path:'../images/gift-tile-OAG.jpg',
            url:'http://www.olivesandgrace.com/'
          }
        ],
        services:[
          {
            path:'../images/gift-tile-USS.jpg',
            url:'http://www.theursulines.org/2013/10/14/in-need-of-prayer/'
          }
        ],
        perpetual:[
          {
            path:'../images/gift-tile-CAS.jpg',
            url:'http://www.kilbey-kennedy.com/p/steve-kilbey-martin-kennedy-write-song.html'
          }
        ]
      }
    };
  });
